version: '3.8'

services:

  nginx:
    build: ./nginx
    ports:
      - "4500:80"
    depends_on:
      - php
    networks:
      - app-network

  php:
    build: ./php
    deploy:
      replicas: 3
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
